#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src

# projectpier
VERSION="pp088wSP2_2014-08-14.zip"
URL="http://www.projectpier.org/files/$VERSION"
dl $URL $SRC


# kamppro2
dl https://github.com/dbernar1/kampPro2/archive/master.zip $SRC
mv $SRC/master.zip $SRC/kampPro2.zip

