#!/bin/bash -ex

DB_NAME=projectpier
DB_USER=projectpier
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/projectpier

# unpack projectpier
unzip -q $SRC/pp*.zip -d $WEBROOT
#mv $WEBROOT/pp* $WEBROOT
chown -R www-data:www-data $WEBROOT
rm $SRC/pp*.zip

# start mysql server
service mysql start

# create the database and user
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
CREATE DATABASE $DB_NAME;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
ON $DB_NAME.*
TO $DB_USER@localhost
IDENTIFIED BY '$DB_PASS';
FLUSH PRIVILEGES;
EOF

# setup apache configuration and complete installation
a2dissite 000-default
a2ensite projectpier
a2enmod rewrite

# complete projectpier installation
service apache2 start

CURL="curl -c /tmp/cookie -b /tmp/cookie"
STEP="http://127.0.0.1/public/install/index.php?step="
DATA="config_form%5Bdatabase_type%5D=mysql&config_form%5Bdatabase_host%5D=localhost&config_form%5Bdatabase_user%5D=$DB_USER&config_form%5Bdatabase_pass%5D=$DB_PASS&config_form%5Bdatabase_name%5D=$DB_NAME&config_form%5Bdatabase_create%5D=no&config_form%5Bdatabase_charset%5D=utf8&config_form%5Bdatabase_prefix%5D=&submitted=submitted"


$CURL ${STEP}1 && $CURL --data "submitted=submitted" ${STEP}1
$CURL ${STEP}2 && $CURL --data "submitted=submitted" ${STEP}2
$CURL ${STEP}3 && $CURL --data $DATA ${STEP}3
$CURL ${STEP}4

rm -f /tmp/cookie

# configure projectpier to use a dynamic hostname and ssl
CONF=$WEBROOT/config/config.php
sed -i "s|define('ROOT_URL', \(.*\)|\$protocol='http://';\n  if (isset(\$_SERVER['HTTPS'])) { \$protocol='https://'; }\n  define('ROOT_URL', \$protocol.\$_SERVER['HTTP_HOST']);|" $CONF

# tweak default theme to display credit text (default is white on white)
CSSDIR=$WEBROOT/public/assets/themes/marine/stylesheets
for FILE in dialog.css complete_install.css; do
    cat >>$CSSDIR/$FILE<<EOF

#turnkey-credit a {
	color: #000066;
	font-weight: normal;
}
EOF
done

# install and configure kampPro2 as default theme
THEMES_DIR=$WEBROOT/public/assets/themes
unzip -q $SRC/kampPro2.zip -d $THEMES_DIR
mv $THEMES_DIR/kampPro2-master $THEMES_DIR/kampPro2
mv $SRC/kampPro2/stylesheets/complete_install.css $THEMES_DIR/kampPro2/stylesheets
rm -rf $SRC/kampPro2*

mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE $DB_NAME;
UPDATE config_options SET value = 'kampPro2' WHERE name = 'theme';
UPDATE config_options SET value = 'TurnKey ProjectPier' WHERE name = 'product_name' OR name = 'site_name';

INSERT INTO users VALUES (1,'admin','admin@example.com','af8c475dfb7554b9976628ef11bb02ab29ba5ef4','16e2639d001f7','9847163250',NOW(),0,NOW(),0,NOW(),NOW(),NOW(),1,1,0);
INSERT INTO contacts VALUES (1,1,1,'admin@example.com','admin','','','','','',0,0,0.00,'','','','','','','','','',NOW(),0,NOW(),0);
INSERT INTO companies VALUES (1,0,'TurnKey ProjectPier','','','','','','','','','','','','',0,0.00,0,NOW(),1,NOW(),0);
EOF

# stop mysql server
service apache2 stop
service mysql stop

rm $WEBROOT/cache/autoloader.php

