#!/bin/bash -ex

DB_NAME=projectpier
DB_USER=projectpier
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/projectpier

# unpack projectpier
unzip -q $SRC/pp*.zip -d $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/pp* $WEBROOT
chown -R www-data:www-data $WEBROOT
rm $SRC/pp*.zip

# workaround innodb crap during build!
rm -f /var/lib/mysql/ib_logfile*

# start mysql server
/etc/init.d/mysql start

# create the database and user
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
CREATE DATABASE $DB_NAME;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
ON $DB_NAME.*
TO $DB_USER@localhost
IDENTIFIED BY '$DB_PASS';
FLUSH PRIVILEGES;
EOF

# setup apache configuration and complete installation
a2dissite default
a2ensite projectpier

# complete projectpier installation
/etc/init.d/apache2 start

CURL="curl -c /tmp/cookie -b /tmp/cookie"
STEP="http://127.0.0.1/public/install/index.php?step="

$CURL ${STEP}1 && $CURL --data "submitted=submitted" ${STEP}1
$CURL ${STEP}2 && $CURL --data "submitted=submitted" ${STEP}2
$CURL ${STEP}3 && $CURL --data "config_form%5Bdatabase_type%5D=mysql&config_form%5Bdatabase_host%5D=localhost&config_form%5Bdatabase_user%5D=$DB_USER&config_form%5Bdatabase_pass%5D=$DB_PASS&config_form%5Bdatabase_name%5D=$DB_NAME&config_form%5Bdatabase_prefix%5D=&config_form%5Babsolute_url%5D=http%3A%2F%2F127.0.0.1&submitted=submitted" ${STEP}3
$CURL ${STEP}4

rm -f /tmp/cookie
/etc/init.d/apache2 stop

# configure projectpier to use a dynamic hostname and ssl
CONF=$WEBROOT/config/config.php
sed -i "s|define('ROOT_URL', \(.*\)|\$protocol='http://';\n  if (isset(\$_SERVER['HTTPS'])) { \$protocol='https://'; }\n  define('ROOT_URL', \$protocol.\$_SERVER['HTTP_HOST']);|" $CONF

# tweak text for admin account creation
CONF=$WEBROOT/language/en_us/site_interface.php

sed -i "s|'complete installation' \(.*\)|'complete installation' => 'Create admin account',|" $CONF

sed -i "s|'complete installation desc' \(.*\)|'complete installation desc' => 'To get started with TurnKey ProjectPier create your administrator account and specify your company name.',|" $CONF

# tweak default theme to display credit text (default is white on white)
CSSDIR=$WEBROOT/public/assets/themes/marine/stylesheets
for FILE in dialog.css complete_install.css; do
    cat >>$CSSDIR/$FILE<<EOF

#turnkey-credit a {
	color: #000066;
	font-weight: normal;
}
EOF
done

# install and configure kampPro2 as default theme
THEMES_DIR=$WEBROOT/public/assets/themes
unzip -q $SRC/kampPro2.zip -d $THEMES_DIR
mv $THEMES_DIR/kampPro2-master $THEMES_DIR/kampPro2
mv $SRC/kampPro2/stylesheets/complete_install.css $THEMES_DIR/kampPro2/stylesheets
rm -rf $SRC/kampPro2*

mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE $DB_NAME;
UPDATE config_options SET
value = 'kampPro2'
WHERE config_handler_class= 'ThemeConfigHandler';
EOF

# stop mysql server
/etc/init.d/mysql stop

# workaround innodb crap during build!
rm -f /var/lib/mysql/ib_logfile*

