#!/bin/bash -ex

NAME=projectpier
DB_PREFIX=pp_
DB_PASSWORD=$(mcookie)

DEST=/var/www/projectpier

# unpack projectpier
unzip /usr/local/src/projectpier.zip -d /usr/local/src/
mv /usr/local/src/projectpier-* $DEST
chown -R www-data:www-data $DEST

sed -i "s/gmt/GMT/" $DEST/public/install/include.php

# workaround innodb crap during build!
rm -f /var/lib/mysql/ib_logfile*

# start mysql server
/etc/init.d/mysql start

# create the database and user
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
CREATE DATABASE $NAME;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
ON $NAME.*
TO $NAME@localhost
IDENTIFIED BY '$DB_PASSWORD';
FLUSH PRIVILEGES;
EOF

# setup apache configuration and complete installation
a2dissite default
a2ensite projectpier

# complete projectpier installation
/etc/init.d/apache2 start

CURL="curl -c /tmp/cookie -b /tmp/cookie"
STEP="http://127.0.0.1/public/install/index.php?step="

$CURL ${STEP}1 && $CURL --data "submited=submited" ${STEP}1
$CURL ${STEP}2 && $CURL --data "submited=submited" ${STEP}2
$CURL ${STEP}3 && $CURL --data "config_form%5Bdatabase_type%5D=mysql&config_form%5Bdatabase_host%5D=localhost&config_form%5Bdatabase_user%5D=$NAME&config_form%5Bdatabase_pass%5D=$DB_PASSWORD&config_form%5Bdatabase_name%5D=$NAME&config_form%5Bdatabase_prefix%5D=$DB_PREFIX&config_form%5Babsolute_url%5D=http%3A%2F%2F127.0.0.1&submited=submited" ${STEP}3
$CURL ${STEP}4

/etc/init.d/apache2 stop

# configure projectpier to use a dynamic hostname and ssl
CONF=$DEST/config/config.php
sed -i "s|define('ROOT_URL', \(.*\)|\$protocol='http://';\n  if (isset(\$_SERVER['HTTPS'])) { \$protocol='https://'; }\n  define('ROOT_URL', \$protocol.\$_SERVER['HTTP_HOST']);|" $CONF

# tweak text for admin account creation
CONF=$DEST/language/en_us/site_interface.php

sed -i "s|'complete installation' \(.*\)|'complete installation' => 'Create admin account',|" $CONF

sed -i "s|'complete installation desc' \(.*\)|'complete installation desc' => 'To get started with TurnKey ProjectPier create your administrator account and specify your company name.',|" $CONF

# tweak default theme to display credit text (default is white on white)
CSSDIR=$DEST/public/assets/themes/default/stylesheets
for FILE in dialog.css complete_install.css; do
    cat >>$CSSDIR/$FILE<<EOF

#turnkey-credit a {
	color: #000066;
	font-weight: normal;
}
EOF
done

# install and configure kampPro as default theme
unzip /usr/local/src/kampPro.zip -d $DEST/public/assets/themes/
mv /usr/local/src/complete_install.css $DEST/public/assets/themes/kampPro/stylesheets

mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE $NAME;
UPDATE pp_config_options SET
value = 'kampPro'
WHERE config_handler_class= 'ThemeConfigHandler';
EOF

# stop mysql server
/etc/init.d/mysql stop

# workaround innodb crap during build!
rm -f /var/lib/mysql/ib_logfile*

# cleanup
rm -rf /usr/local/src/projectpier*
rm -rf /usr/local/src/kampPro*
rm -f /tmp/cookie

