#!/bin/bash -e
# regenerate projectpier token and mysql password

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/projectpier/config/config.php
    sed -i "s/\(.*\)$1\(.*\)');/  define('$1', '$2');/;" $CONF
}

updateconf 'TOKEN_COOKIE_NAME' $(mcookie)$(mcookie)

PASSWORD=$(mcookie)
updateconf 'DB_PASS' $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=projectpier --pass="$PASSWORD"

