#!/bin/bash -e
# set projectpier admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/projectpier.py --pass="$APP_PASS" --email="$APP_EMAIL"

